# Stubs for advanced_descriptors.separate_class_method (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import typing

class SeparateClassMethod:
    def __init__(
            self,
            imeth: typing.Optional[typing.Callable[..., typing.Any]]=None,
            cmeth: typing.Optional[typing.Callable[..., typing.Any]]=None,
    ) -> None: ...

    def class_method(self, cmeth: typing.Optional[typing.Callable[..., typing.Any]]) -> SeparateClassMethod: ...

    def instance_method(self, imeth: typing.Optional[typing.Callable[..., typing.Any]]) -> SeparateClassMethod: ...

    @property
    def cmeth(self) -> typing.Optional[typing.Callable[..., typing.Any]]: ...

    @property
    def imeth(self) -> typing.Optional[typing.Callable[..., typing.Any]]: ...

    def __get__(self, instance: typing.Optional[object], owner: typing.Type[object]) -> typing.Callable[..., typing.Any]: ...
